### ISSUE TITLE
Game Updated, crashes on startup with modding API enabled.

### ISSUE THREAD

**Issue by Ryuzaki413** [HollowKnight-Modding/HollowKnight.Modding#48]

**Comment by fifty-six** [comment]
Please use an up-to-date build. The releases are not yet on 1.5.

**Comment by kainsavage** [comment]
Does this mean that I have to build it myself on the new v1.5.68.11808 Hollow Knight to get mods working again, or is there a plan for a new release in the next couple days?

**Comment by fifty-six** [comment]
You can grab the build with the artifact off of CI, release date is still out of the picture for now

**Comment by kainsavage** [comment]
I'm getting errors when trying to load any mod (like ModCommon, for instance) with the latest build artifact. It says to check ModLog.txt, but I cannot find this file.

**Comment by fifty-six** [comment]
ModLog is in the saves folder like normal. Mods not loading is expected as 1.5 is a breaking change and we changed a lot of the api as well while we had the chance.
